version: '3'
services:
  app:
    build: .
    command: "python manage.py runserver 0.0.0.0:8000"
    networks: 
      - frontend
    volumes:
      - .:/eat-today-bucharest
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: razvancir96/mysql01:latest
    ports:
      - "3306:3306"
    networks:
      - frontend
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'bd2'
      MYSQL_USER: 'razvan'
      MYSQL_PASSWORD: 'razvan'

networks: 
  frontend:

  