# Generated by Django 2.1.4 on 2019-01-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DmlLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=700)),
                ('date_dml', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'dml_logs',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=40)),
                ('esurname', models.CharField(max_length=40)),
                ('job', models.CharField(max_length=40)),
                ('hiredate', models.DateField(blank=True, null=True)),
                ('is_admin', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=13)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'restaurant',
            },
        ),
        migrations.CreateModel(
            name='TodaysMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('start_hour', models.TimeField(blank=True, null=True)),
                ('end_hour', models.TimeField(blank=True, null=True)),
                ('soup', models.CharField(blank=True, max_length=50, null=True)),
                ('main_course', models.CharField(blank=True, max_length=50, null=True)),
                ('side', models.CharField(blank=True, max_length=50, null=True)),
                ('salad', models.CharField(blank=True, max_length=50, null=True)),
                ('dessert', models.CharField(blank=True, max_length=50, null=True)),
                ('drink', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('is_mixed', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'todays_menu',
            },
        ),
        migrations.CreateModel(
            name='TodaysMenuCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('start_hour', models.TimeField(blank=True, null=True)),
                ('end_hour', models.TimeField(blank=True, null=True)),
                ('soup', models.CharField(blank=True, max_length=50, null=True)),
                ('main_course', models.CharField(blank=True, max_length=50, null=True)),
                ('side', models.CharField(blank=True, max_length=50, null=True)),
                ('salad', models.CharField(blank=True, max_length=50, null=True)),
                ('dessert', models.CharField(blank=True, max_length=50, null=True)),
                ('drink', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('is_mixed', models.IntegerField(blank=True, null=True)),
                ('id_restaurant', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'todays_menu_copy',
            },
        ),
    ]
